name = "csp"
main = "src/index.js"
compatibility_date = "2024-04-04"
workers_dev = true

[[d1_databases]]
binding = "d1"
database_name = "{updateme}"
database_id = "{update_me}"

[triggers]
crons = ["0 0 * * 2"]

[vars]
MAILGUN_API_KEY = ""
FROM_EMAIL_ADDRESS = ""
TO_EMAIL_ADDRESS = ""
MAILGUN_DOMAIN = ""